AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  macro-acct-integration

  SAM Template for macro-acct-integration

Globals:
  Function:
    Runtime: python3.9
    Timeout: 3
    Handler: main.handler

Parameters:
  SnsTopicArn:
    Type: String

  SnsRegion:
    Type: String

  SnsPolicyRole:
    Type: String

  TargetS3Bucket:
    Type: String

  TargetBucketRole:
    Type: String

Resources:
  HandleMacroSNSEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handle_macro_sns_event/
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Region: !Ref SnsRegion
            Topic: !Ref SnsTopicArn





Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out mor1e about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
