AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  macro-acct-integration

  SAM Template for macro-acct-integration

Globals:
  Function:
    Runtime: python3.9
    Timeout: 3
    Role: !GetAtt BucketIamRole.Arn
    Handler: main.handler

Parameters:
  SnsTopicArn:
    Type: String

  SnsRegion:
    Type: String

  SnsPolicyRole:
    Type: String

  MacroscopeS3Bucket:
    Type: String

  SourceBucketRole:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  BucketIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: lambda_s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Effect: Allow
              Action:
                - s3:Delete*
                - s3:Get*
                - s3:List*
                - s3:Put*
              Resource: !GetAtt S3Bucket.Arn

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Shared functionality between lambdas
      ContentUri: layers/shared
    Metadata:
      BuildMethod: python3.8

  HandleMacroSNSEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handle_macro_sns_event/
      Environment:
        Variables:
          SOURCE_S3_BUCKET: !Ref MacroscopeS3Bucket
          SOURCE_S3_BUCKET_ROLE: !Ref MacroscopeS3BucketRole
          TARGET_S3_BUCKET: !Ref S3Bucket
      Layers:
        - !Ref SharedLayer
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Region: !Ref SnsRegion
            Topic: !Ref SnsTopicArn

  HandleS3EventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handle_s3_event/
      Environment:
        Variables:
          TARGET_S3_BUCKET: !Ref MacroscopeS3Bucket
          TARGET_S3_BUCKET_ROLE: !Ref MacroscopeS3BucketRole
          SOURCE_S3_BUCKET: !Ref S3Bucket
      Layers:
        - !Ref SharedLayer
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events:
              - s3:ObjectCreated:*
